name: Feature CI

on:
  workflow_dispatch:
  push:
    branches: [ 'feature/**' ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pkgxdev/setup@v4
        with:
          +: nodejs.org@24 pnpm.io@10.15.1
      - run: pnpm install
      - run: pnpm audit
      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm run test
      - run: pnpm run test-node

# TODO: Добавить ${{ matrix.node-version }} по аналогии с тут: https://github.com/ydb-platform/ydb-js-sdk/blob/main/.github/workflows/ci.yml
